version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: docengine_postgres
    environment:
      POSTGRES_USER: docengine
      POSTGRES_PASSWORD: docengine123
      POSTGRES_DB: docengine_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: docengine_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data:
